name: SURE-Pipe
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # Core Python
  - python
  - openjdk=17

  # Bioinformatics tools
  - bedtools
  - blast
  - seqkit
  - samtools
  - graphviz
  - parallel

  # Python packages
  - pandas      # Install this because your env is missing pandas
  - biopython   # Install this because Bio was missing
